### ISSUE TITLE
Youtube playlists show "no items"

### ISSUE THREAD

**Issue by Biber7** [patrickkfkan/Volumio-YouTube.js#8]
Hello

Since some days I’m unable to play any youtube music content. under youtube music I see “Home”, “Explore”, “Library” and “History” and under “Home”, “Library” and “Explore” i find the playlist as I would find on youtube itself. But after selecting a playlist volumio shows “no items” instead of the content. The songs under “History” can’t be played either

I updated the system and the plugin. I reinstalled the plugin and reconnected to my payed youtube account (all successfully) but the problem persists.

The log entry tells me to post this here ;-)

Thanks and best regards
Nicolaj

Starting Live Log...
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
RRM: Ignoring radio measurement request: Not RRM network
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: Listing playlists
info: Listing playlists
info: CALLMETHOD: system_controller system enableLiveLog true
info: CoreCommandRouter::executeOnPlugin: system , enableLiveLog
info: Launching a new LiveLog session
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
RRM: Ignoring radio measurement request: Not RRM network
RRM: Ignoring radio measurement request: Not RRM network
 volumio : unable to resolve host volumiomaster
 volumio : problem with defaults entries ; TTY=unknown ; PWD=/ ; USER=root ;
 volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig eth0
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
 volumio : unable to resolve host volumiomaster
 volumio : problem with defaults entries ; TTY=unknown ; PWD=/ ; USER=root ;
 volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root

info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: Listing playlists
info: Listing playlists
 volumio : unable to resolve host volumiomaster
 volumio : problem with defaults entries ; TTY=unknown ; PWD=/ ; USER=root ;
 volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig eth0
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
 volumio : unable to resolve host volumiomaster
 volumio : problem with defaults entries ; TTY=unknown ; PWD=/ ; USER=root ;
 volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root

info: CoreCommandRouter::executeOnPlugin: my_volumio , getAutoUpdateCheckEnabled
info: CoreCommandRouter::volumioGetVisibleSources
info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::executeOnPlugin: metavolumio , getInfinityPlayback
info: CoreCommandRouter::executeOnPlugin: multiroom , getMultiroom
info: Error : CoreCommandRouter::executeOnPlugin: No method [getMultiroom] in plugin multiroom
info: Received Get System Info
info: CoreCommandRouter::executeOnPlugin: system , getSystemInfo
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , getThisDevice
info: Discovery: Getting this device information
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::executeOnPlugin: network , getCachedIPAddresses
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: Listing playlists
info: CoreCommandRouter::executeOnPlugin: appearance , getUiSettings
info: CoreCommandRouter::executeOnPlugin: system , getPrivacySettings
info: CoreCommandRouter::executeOnPlugin: updater_comm , getUpdateMessageCache
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::volumioGetQueue
info: CoreStateMachine::getQueue
info: CorePlayQueue::getQueue
info: CoreCommandRouter::executeOnPlugin: wizard , getOnboardingWizard
info: CoreCommandRouter::executeOnPlugin: my_volumio , getMyVolumioStatus
info: Received Get System Info
info: CoreCommandRouter::executeOnPlugin: system , getSystemInfo
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , getThisDevice
info: Discovery: Getting this device information
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::executeOnPlugin: network , getCachedIPAddresses
info: CoreCommandRouter::executeOnPlugin: my_volumio , getMyVolumioStatus
info: Received Get System Info
info: CoreCommandRouter::executeOnPlugin: system , getSystemInfo
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , getThisDevice
info: Discovery: Getting this device information
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::executeOnPlugin: network , getCachedIPAddresses
info: Executing endpoint metavolumio
info: CoreCommandRouter::executeOnPlugin: metavolumio , requestToMetaVolumio
info: Executing endpoint metavolumio
info: CoreCommandRouter::executeOnPlugin: metavolumio , requestToMetaVolumio
info: Executing endpoint metavolumio
info: CoreCommandRouter::executeOnPlugin: metavolumio , requestToMetaVolumio
info: CoreCommandRouter::executeOnPlugin: ytmusic , handleBrowseUri
info: [ytmusic-browse] browseUri: ytmusic/generic@endpoint:o=%7B%22type%22%3A%22browse%22%2C%22payload%22%3A%7B%22browseId%22%3A%22FEmusic_explore%22%7D%7D/generic@endpoint:o=%7B%22type%22%3A%22browse%22%2C%22payload%22%3A%7B%22browseId%22%3A%22FEmusic_moods_and_genres%22%7D%7D/generic@endpoint:o=%7B%22type%22%3A%22browse%22%2C%22payload%22%3A%7B%22browseId%22%3A%22FEmusic_moods_and_genres_category%22%2C%22params%22%3A%22ggMPOg1uX1NPTld3SDN3WGs4%22%7D%7D/playlist@endpoints:o=%7B%22watch%22%3A%7B%22type%22%3A%22watch%22%2C%22payload%22%3A%7B%22playlistId%22%3A%22RDCLAK5uy_nHGuTnohZ82uuk0HQle7s-UgP7h3aoCqg%22%2C%22params%22%3A%22wAEB%22%7D%7D%2C%22browse%22%3A%7B%22type%22%3A%22browse%22%2C%22payload%22%3A%7B%22browseId%22%3A%22VLRDCLAK5uy_nHGuTnohZ82uuk0HQle7s-UgP7h3aoCqg%22%7D%2C%22pageType%22%3A%22MUSIC_PAGE_TYPE_PLAYLIST%22%7D%7D
InnertubeError: Something went wrong at MusicResponsiveHeader!
This is a bug, please report it at https://github.com/patrickkfkan/Volumio-YouTube.js/issues
    at Function._Parser_printError (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18226:16)
    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18059:70)
    at Function.parseArray (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18069:29)
    at new SectionList (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:16343:36)
    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)
    at new Tab (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:16592:35)
    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)
    at Function.parse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18086:29)
    at new TwoColumnBrowseResults (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:16943:32)
    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)
    at Function.parse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18096:39)
    at Function.parseResponse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:17864:27)
    at PlaylistModel._EndpointModel_doGetContents (/data/plugins/music_service/ytmusic/dist/lib/model/EndpointModel.js:43:49)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PlaylistModel.getContents (/data/plugins/music_service/ytmusic/dist/lib/model/PlaylistModel.js:26:26) {
  info: {
    stack: 'TypeError: inference_type.renderers.map is not a function\n' +
      '    at Function.toTypeDeclaration (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:17566:58)\n' +
      '    at Function.generateTypescriptClass (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:17546:68)\n' +
      '    at Function._YTNodeGenerator_logChangedKeys (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:17765:8)\n' +
      '    at new MusicResponsiveHeader (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:17496:93)\n' +
      '    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)\n' +
      '    at Function.parseArray (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18069:29)\n' +
      '    at new SectionList (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:16343:36)\n' +
      '    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)\n' +
      '    at new Tab (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:16592:35)\n' +
      '    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)\n' +
      '    at Function.parse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18086:29)\n' +
      '    at new TwoColumnBrowseResults (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:16943:32)\n' +
      '    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)\n' +
      '    at Function.parse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:18096:39)\n' +
      '    at Function.parseResponse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/bundle/node.cjs:17864:27)\n' +
      '    at PlaylistModel._EndpointModel_doGetContents (/data/plugins/music_service/ytmusic/dist/lib/model/EndpointModel.js:43:49)'
  },
  date: 2024-08-06T05:41:47.011Z,
  version: '0.3.3'
}
info: Preload queue cleared
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::executeOnPlugin: appearance , isLatestTOSAccepted
info: CoreCommandRouter::executeOnPlugin: system , getPrivacySettings
info: CALLMETHOD: system_controller my_volumio retreiveBackendEventStates undefined
info: CoreCommandRouter::executeOnPlugin: my_volumio , retreiveBackendEventStates
info: Received Get System Version
info: CoreCommandRouter::executeOnPlugin: system , getSystemVersion
info: Received Get System Info
info: CoreCommandRouter::executeOnPlugin: system , getSystemInfo
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , getThisDevice
info: Discovery: Getting this device information
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::executeOnPlugin: network , getCachedIPAddresses
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: Listing playlists
info: Listing playlists
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: Listing playlists
info: Listing playlists
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: Listing playlists
info: Listing playlists
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: Listing playlists
info: Listing playlists
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: Listing playlists
info: Listing playlists
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1
info: Listing playlists
info: Listing playlists
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 1

**Comment by patrickkfkan** [comment]
You are not running the latest version. The version of `Volume-YouTube.js` lib shown in your logs is 0.3.3. The latest is 0.3.9.

Follow the instructions here to update the plugin to the latest version:

https://community.volumio.com/t/plugin-youtube-music/57647/200

**Comment by Biber7** [comment]
Thanks! Great job for a great product!
